json.set! :namespace, analysis.namespace
json.set! :name, analysis.name
json.set! :snapshot, analysis.snapshot
json.set! :configuration_namespace, analysis.configuration_namespace
json.set! :configuration_name, analysis.configuration_name
json.set! :configuration_snapshot, analysis.configuration_snapshot
json.set! :synopsis, analysis.synopsis
json.set! :entity_type, analysis.entity_type
json.set! :required_inputs, analysis.required_inputs(true)
